language: java
install:
- |
sudo: false
script: mvn clean verify
script: cp /home/travis/build/ivy-supplements/mavenizer/README.MD /home/travis/build/ivy-supplements/mavenizer/designer.project.maven.p2/target/repository
deploy:
  provider: pages
  local_dir: /home/travis/build/ivy-supplements/mavenizer/designer.project.maven.p2/target/repository
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
